AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  pAppName:
    Type: String
  pEnvironmentName:
    Type: String
    Default: dev
  pDdbStackName:
    Type: String
  pGitHash:
    Type: String
  pGitBranch:
    Type: String

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs22.x
    Handler: index.handler
    Environment:
      Variables:
        HOUSES_TABLE_NAME:
          Fn::ImportValue: !Sub ${pDdbStackName}-HousesTableName

Resources:
  ApiGatewayRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${pAppName}-${pEnvironmentName}-api"
      StageName: !Sub ${pEnvironmentName}

  HousesLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${pAppName}-${pEnvironmentName}-houses-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: DynamoDBPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:Scan
                Resource:
                  - Fn::ImportValue: !Sub ${pDdbStackName}-HousesTableArn
                  - !Join [
                      "/",
                      [
                        Fn::ImportValue: !Sub "${pDdbStackName}-HousesTableArn",
                        "index/*",
                      ],
                    ]
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  GetHousesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${pAppName}-${pEnvironmentName}-get-houses-lambda"
      CodeUri: ../dist/lambdas/house/getList
      Role: !GetAtt HousesLambdaRole.Arn
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /house
            RestApiId: !Ref ApiGatewayRestApi

  AddHouseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${pAppName}-${pEnvironmentName}-add-house-lambda"
      CodeUri: ../dist/lambdas/house/add
      Role: !GetAtt HousesLambdaRole.Arn
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Method: POST
            Path: /house
            RestApiId: !Ref ApiGatewayRestApi

Outputs:
  RestApiUrl:
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${pEnvironmentName}"
    Export:
      Name: !Sub ${AWS::StackName}-RestApiUrl

  HousesLambdaRoleArn:
    Description: "ARN of the Houses Lambda Role"
    Value: !GetAtt HousesLambdaRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-HousesLambdaRoleArn

  GetHousesFunctionName:
    Description: "Name of the Get Houses Lambda Function"
    Value: !Ref GetHousesFunction
    Export:
      Name: !Sub ${AWS::StackName}-GetHousesFunctionName

  GetHousesFunctionNameArn:
    Description: "ARN of the Get Houses Lambda Function"
    Value: !GetAtt GetHousesFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-GetHousesFunctionNameArn

  AddHouseFunctionName:
    Description: "Name of the Add House Lambda Function"
    Value: !Ref AddHouseFunction
    Export:
      Name: !Sub ${AWS::StackName}-AddHouseFunctionName

  AddHouseFunctionNameArn:
    Description: "ARN of the Add House Lambda Function"
    Value: !GetAtt AddHouseFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-AddHouseFunctionNameArn

  CodeRef:
    Value: !Join ["", [!Ref pGitBranch, ".", !Ref pGitHash]]
    Description: Code Reference
    Export:
      Name: !Sub ${AWS::StackName}-CodeRef
