AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  pAppName:
    Type: String
  pEnvironmentName:
    Type: String
    Default: dev
  pDdbStackName:
    Type: String
  pGitHash:
    Type: String
  pGitBranch:
    Type: String

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs22.x
    Handler: index.handler
    Environment:
      Variables:
        THINGS_TABLE_NAME:
          Fn::ImportValue: !Sub ${pDdbStackName}-ThingsTableName

Resources:
  ApiGatewayRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${pAppName}-${pEnvironmentName}-api"
      StageName: !Sub ${pEnvironmentName}
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'OPTIONS,GET,POST,PUT,PATCH,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"

  ThingsLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${pAppName}-${pEnvironmentName}-things-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: DynamoDBPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                Resource:
                  - Fn::ImportValue: !Sub ${pDdbStackName}-ThingsTableArn
                  - !Join [
                      "/",
                      [
                        Fn::ImportValue: !Sub "${pDdbStackName}-ThingsTableArn",
                        "index/*",
                      ],
                    ]
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  GetThingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${pAppName}-${pEnvironmentName}-get-things-lambda"
      CodeUri: ../dist/lambdas/thing/getList
      Role: !GetAtt ThingsLambdaRole.Arn
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /thing
            RestApiId: !Ref ApiGatewayRestApi

  GetThingByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${pAppName}-${pEnvironmentName}-get-thing-by-id-lambda"
      CodeUri: ../dist/lambdas/thing/getById
      Role: !GetAtt ThingsLambdaRole.Arn
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /thing/{id}
            RestApiId: !Ref ApiGatewayRestApi

  CreateThingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${pAppName}-${pEnvironmentName}-create-thing-lambda"
      CodeUri: ../dist/lambdas/thing/create
      Role: !GetAtt ThingsLambdaRole.Arn
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Method: POST
            Path: /thing
            RestApiId: !Ref ApiGatewayRestApi

  UpdateThingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${pAppName}-${pEnvironmentName}-update-thing-lambda"
      CodeUri: ../dist/lambdas/thing/update
      Role: !GetAtt ThingsLambdaRole.Arn
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Method: PUT
            Path: /thing
            RestApiId: !Ref ApiGatewayRestApi

  DeleteThingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${pAppName}-${pEnvironmentName}-delete-thing-lambda"
      CodeUri: ../dist/lambdas/thing/delete
      Role: !GetAtt ThingsLambdaRole.Arn
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Method: DELETE
            Path: /thing/{id}
            RestApiId: !Ref ApiGatewayRestApi

Outputs:
  RestApiUrl:
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${pEnvironmentName}"
    Export:
      Name: !Sub ${AWS::StackName}-RestApiUrl

  ThingsLambdaRoleArn:
    Description: "ARN of the Things Lambda Role"
    Value: !GetAtt ThingsLambdaRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ThingsLambdaRoleArn

  GetThingsFunctionName:
    Description: "Name of the Get Things Lambda Function"
    Value: !Ref GetThingsFunction
    Export:
      Name: !Sub ${AWS::StackName}-GetThingsFunctionName

  GetThingsFunctionNameArn:
    Description: "ARN of the Get Things Lambda Function"
    Value: !GetAtt GetThingsFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-GetThingsFunctionNameArn

  GetThingByIdFunctionName:
    Description: "Name of the Get Thing By Id Lambda Function"
    Value: !Ref GetThingByIdFunction
    Export:
      Name: !Sub ${AWS::StackName}-GetThingByIdFunctionName

  GetThingByIdFunctionNameArn:
    Description: "ARN of the Get Thing By Id Lambda Function"
    Value: !GetAtt GetThingByIdFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-GetThingByIdFunctionNameArn

  CreateThingFunctionName:
    Description: "Name of the Create Thing Lambda Function"
    Value: !Ref CreateThingFunction
    Export:
      Name: !Sub ${AWS::StackName}-CreateThingFunctionName

  CreateThingFunctionNameArn:
    Description: "ARN of the Create Thing Lambda Function"
    Value: !GetAtt CreateThingFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-CreateThingFunctionNameArn

  UpdateThingFunctionName:
    Description: "Name of the Update Thing Lambda Function"
    Value: !Ref UpdateThingFunction
    Export:
      Name: !Sub ${AWS::StackName}-UpdateThingFunctionName

  UpdateThingFunctionNameArn:
    Description: "ARN of the Update Thing Lambda Function"
    Value: !GetAtt UpdateThingFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-UpdateThingFunctionNameArn

  DeleteThingFunctionName:
    Description: "Name of the Delete Thing Lambda Function"
    Value: !Ref DeleteThingFunction
    Export:
      Name: !Sub ${AWS::StackName}-DeleteThingFunctionName

  DeleteThingFunctionNameArn:
    Description: "ARN of the Delete Thing Lambda Function"
    Value: !GetAtt DeleteThingFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-DeleteThingFunctionNameArn

  CodeRef:
    Value: !Join ["", [!Ref pGitBranch, ".", !Ref pGitHash]]
    Description: Code Reference
    Export:
      Name: !Sub ${AWS::StackName}-CodeRef
