AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  pAppName:
    Type: String
  pEnvironmentName:
    Type: String
    Default: dev
  pGitHash:
    Type: String
  pGitBranch:
    Type: String

Resources:
  ApiGatewayRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${pAppName}-${pEnvironmentName}-api"
      StageName: !Sub ${pEnvironmentName}

  LambdaFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${pAppName}-${pEnvironmentName}-api-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  LambdaFunctionApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${pAppName}-${pEnvironmentName}-api-lambda"
      CodeUri: ../dist/lambdas/helloWorld
      Handler: index.handler
      Runtime: nodejs22.x
      Role: !GetAtt LambdaFunctionRole.Arn
      Events:
        RestApiEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /
            RestApiId: !Ref ApiGatewayRestApi

Outputs:
  RestApiUrl:
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${pEnvironmentName}"
    Export:
      Name: !Sub ${AWS::StackName}-RestApiUrl

  ApiFunctionName:
    Description: "Name of the API Lambda Function"
    Value: !Ref LambdaFunctionApi
    Export:
      Name: !Sub ${AWS::StackName}-ApiFunctionName

  ApiFunctionArn:
    Description: "ARN of the API Lambda Function"
    Value: !GetAtt LambdaFunctionApi.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ApiFunctionArn

  CodeRef:
    Value: !Join ["", [!Ref pGitBranch, ".", !Ref pGitHash]]
    Description: Code Reference
    Export:
      Name: !Sub ${AWS::StackName}-CodeRef
