AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  pAppName:
    Type: String
  pEnvironmentName:
    Type: String
    Default: dev
  pGitHash:
    Type: String
  pGitBranch:
    Type: String

Resources:
  ThingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${pAppName}-${pEnvironmentName}-things"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

Outputs:
  ThingsTableName:
    Description: "Name of the Things DynamoDB Table"
    Value: !Ref ThingsTable
    Export:
      Name: !Sub ${AWS::StackName}-ThingsTableName

  ThingsTableArn:
    Description: "ARN of the Things DynamoDB Table"
    Value: !GetAtt ThingsTable.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ThingsTableArn

  CodeRef:
    Value: !Join ["", [!Ref pGitBranch, ".", !Ref pGitHash]]
    Description: Code Reference
    Export:
      Name: !Sub ${AWS::StackName}-CodeRef
