AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  pAppName:
    Type: String
    Description: Application Name deployed in this stack
  pEnvironmentName:
    Type: String
    Default: dev
    Description: The name of the specific stack deployment e.g. 'dev'
  pImageUri:
    Type: String
    Description: The ECR Image URI
  pVpcId:
    Type: String
    Description: VPC ID for security group
  pPrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of the private subnets in the VPC
  pELBSecurityGroupId:
    Type: String
    Description: Security Group ID of the Load Balancer
  pELBStackName:
    Type: String
    Description: ELB Stack Name to import target group ARNs
  pDdbStackName:
    Type: String
  pCognitoStackName:
    Type: String
  pContainerPort:
    Type: Number
    Default: 4000
  pTaskCount:
    Type: Number
    Default: 1
  pGitHash:
    Type: String
  pGitBranch:
    Type: String

Resources:
  IAMRoleEcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${pAppName}-${pEnvironmentName}-EcsTaskRole
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      Policies:
        - PolicyName: DynamoDBPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                Resource:
                  - Fn::ImportValue: !Sub ${pDdbStackName}-ThingsTableArn
                  - !Join ["/", [Fn::ImportValue: !Sub "${pDdbStackName}-ThingsTableArn", "index/*"]]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs

  IAMRoleEcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${pAppName}-${pEnvironmentName}-EcsTaskExecutionRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${pAppName}-${pEnvironmentName}-EcsCluster
      CapacityProviders:
        - FARGATE
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT

  TaskDefinitionA:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${pAppName}-${pEnvironmentName}-a-TaskDefinition
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt IAMRoleEcsTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt IAMRoleEcsTaskRole.Arn
      ContainerDefinitions:
        - Name: !Sub ${pAppName}-${pEnvironmentName}-a-container
          Image: !Sub ${pImageUri}
          PortMappings:
            - ContainerPort: !Sub ${pContainerPort}
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: !Sub ${pEnvironmentName}
            - Name: PORT
              Value: !Sub ${pContainerPort}
            - Name: THINGS_TABLE_NAME
              Value:
                Fn::ImportValue: !Sub ${pDdbStackName}-ThingsTableName
            - Name: COGNITO_USER_POOL_ID
              Value:
                Fn::ImportValue: !Sub ${pCognitoStackName}-UserPoolId
            - Name: COGNITO_CLIENT_ID
              Value:
                Fn::ImportValue: !Sub ${pCognitoStackName}-UserPoolClientId
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: !Sub /ecs/${pAppName}-${pEnvironmentName}-a
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs

  ECSClusterSecurityGroupA:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for ECS Service A
      GroupName: !Sub ${pAppName}-${pEnvironmentName}-a-ecs-sg
      VpcId: !Ref pVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Sub ${pContainerPort}
          ToPort: !Sub ${pContainerPort}
          SourceSecurityGroupId: !Ref pELBSecurityGroupId

  ECSServiceA:
    Type: AWS::ECS::Service
    DependsOn: ECSClusterSecurityGroupA
    Properties:
      ServiceName: !Sub ${pAppName}-${pEnvironmentName}-a-EcsService
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref pTaskCount
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinitionA
      LoadBalancers:
        - ContainerName: !Sub ${pAppName}-${pEnvironmentName}-a-container
          ContainerPort: !Sub ${pContainerPort}
          TargetGroupArn:
            Fn::ImportValue: !Sub ${pELBStackName}-ELBTargetGroupAArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ECSClusterSecurityGroupA
          Subnets: !Ref pPrivateSubnetIds

  TaskDefinitionB:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${pAppName}-${pEnvironmentName}-b-TaskDefinition
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt IAMRoleEcsTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt IAMRoleEcsTaskRole.Arn
      ContainerDefinitions:
        - Name: !Sub ${pAppName}-${pEnvironmentName}-b-container
          Image: !Sub ${pImageUri}
          PortMappings:
            - ContainerPort: !Sub ${pContainerPort}
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: !Sub ${pEnvironmentName}
            - Name: PORT
              Value: !Sub ${pContainerPort}
            - Name: THINGS_TABLE_NAME
              Value:
                Fn::ImportValue: !Sub ${pDdbStackName}-ThingsTableName
            - Name: COGNITO_USER_POOL_ID
              Value:
                Fn::ImportValue: !Sub ${pCognitoStackName}-UserPoolId
            - Name: COGNITO_CLIENT_ID
              Value:
                Fn::ImportValue: !Sub ${pCognitoStackName}-UserPoolClientId
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: !Sub /ecs/${pAppName}-${pEnvironmentName}-b
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs

  ECSClusterSecurityGroupB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for ECS Service B
      GroupName: !Sub ${pAppName}-${pEnvironmentName}-b-ecs-sg
      VpcId: !Ref pVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Sub ${pContainerPort}
          ToPort: !Sub ${pContainerPort}
          SourceSecurityGroupId: !Ref pELBSecurityGroupId

  ECSServiceB:
    Type: AWS::ECS::Service
    DependsOn: ECSClusterSecurityGroupB
    Properties:
      ServiceName: !Sub ${pAppName}-${pEnvironmentName}-b-EcsService
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref pTaskCount
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinitionB
      LoadBalancers:
        - ContainerName: !Sub ${pAppName}-${pEnvironmentName}-b-container
          ContainerPort: !Sub ${pContainerPort}
          TargetGroupArn:
            Fn::ImportValue: !Sub ${pELBStackName}-ELBTargetGroupBArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ECSClusterSecurityGroupB
          Subnets: !Ref pPrivateSubnetIds

Outputs:
  EcsTaskRoleArn:
    Description: ECS Task Role ARN
    Value: !GetAtt IAMRoleEcsTaskRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EcsTaskRoleArn"

  EcsClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${AWS::StackName}-EcsClusterName"

  EcsClusterArn:
    Description: ECS Cluster ARN
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EcsClusterArn"

  EcsTaskExecutionRoleArn:
    Description: ECS Task Execution Role ARN
    Value: !GetAtt IAMRoleEcsTaskExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EcsTaskExecutionRoleArn"

  EcsTaskDefinitionAArn:
    Description: ECS Task Definition A ARN
    Value: !GetAtt TaskDefinitionA.TaskDefinitionArn
    Export:
      Name: !Sub "${AWS::StackName}-EcsTaskDefinitionAArn"

  EcsTaskDefinitionBArn:
    Description: ECS Task Definition B ARN
    Value: !GetAtt TaskDefinitionB.TaskDefinitionArn
    Export:
      Name: !Sub "${AWS::StackName}-EcsTaskDefinitionBArn"

  ECSClusterSecurityGroupAId:
    Description: ECS Cluster Security Group A ID
    Value: !GetAtt ECSClusterSecurityGroupA.GroupId
    Export:
      Name: !Sub "${AWS::StackName}-EcsClusterSecurityGroupAId"

  ECSClusterSecurityGroupBId:
    Description: ECS Cluster Security Group B ID
    Value: !GetAtt ECSClusterSecurityGroupB.GroupId
    Export:
      Name: !Sub "${AWS::StackName}-EcsClusterSecurityGroupBId"

  EcsServiceAName:
    Description: ECS Service A Name
    Value: !GetAtt ECSServiceA.Name
    Export:
      Name: !Sub "${AWS::StackName}-EcsServiceAName"

  EcsServiceAArn:
    Description: ECS Service A ARN
    Value: !GetAtt ECSServiceA.ServiceArn
    Export:
      Name: !Sub "${AWS::StackName}-EcsServiceAArn"

  EcsServiceBName:
    Description: ECS Service B Name
    Value: !GetAtt ECSServiceB.Name
    Export:
      Name: !Sub "${AWS::StackName}-EcsServiceBName"

  EcsServiceBArn:
    Description: ECS Service B ARN
    Value: !GetAtt ECSServiceB.ServiceArn
    Export:
      Name: !Sub "${AWS::StackName}-EcsServiceBArn"

  CodeRef:
    Value: !Join ["", [!Ref pGitBranch, ".", !Ref pGitHash]]
    Description: Code Reference
    Export:
      Name: !Sub ${AWS::StackName}-CodeRef
