name: Deploy All

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose development environment to deploy
        options:
          - dev
          - test
          - prod
        default: dev
      backend:
        type: choice
        description: Choose backend service to deploy
        options:
          - lambda
          - ecs
        default: lambda
      deploy_ecr:
        type: boolean
        description: Deploy new ECR image?
        default: false
      region:
        type: string
        description: Choose AWS region
        default: ap-southeast-2

permissions:
  id-token: write
jobs:
  deploy-infra-lambda:
    if: github.event.inputs.backend == 'lambda'
    uses: ./.github/workflows/all-lambda.yml
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
      region: ${{ github.event.inputs.region }}

  deploy-infra-ecs:
    if: github.event.inputs.backend == 'ecs'
    uses: ./.github/workflows/all-ecs.yml
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
      region: ${{ github.event.inputs.region }}
      deploy_ecr: ${{ github.event.inputs.deploy_ecr }}
