name: Deploy Infra Common Resources

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose development environment to deploy
        options:
          - dev
          - test
          - prod
        default: dev
      region:
        type: string
        description: Choose AWS region
        default: ap-southeast-2
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      region:
        required: true
        type: string

permissions:
  id-token: write
jobs:
  deploy:
    name: "Deploy Infrastructure"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Running script for common resources deployment
        id: deploy-common
        working-directory: ./backend
        env:
          AWS_REGION: ${{ github.event.inputs.region }}
          ENVIRONMENT_NAME: ${{ github.event.inputs.environment }}
        run: |
          chmod u+x deploy-common.sh
          ./deploy-common.sh
